---
permalink: upgrade/upgrade-considerations.html
sidebar: sidebar
keywords: plan, upgrade, consideration, contact, technical, support, recommendation, guidance, cluster, considerations for upgrading controller hardware
summary: To plan for the upgrade, you should familiarize yourself with the general upgrade considerations. If necessary, contact technical support for recommendations and guidance specific to the configuration of your cluster.
---
= Considerations for upgrading controller hardware
:icons: font
:imagesdir: ../media/

[.lead]
To plan for the upgrade, you must familiarize yourself with the general upgrade considerations. If necessary, contact technical support for recommendations and guidance specific to the configuration of your cluster.

== Requirements and limitations

Depending on your environment, you need to consider certain factors before you start your upgrade. Get started by reviewing the table below to see the requirements and limitations you need to consider.

[cols=2*,options="header",cols="30,70"]
|===
|Ask yourself... |If your answer is yes, then do this..
|Do I have different software versions running on the original and new nodes?
a|*  https://hwu.netapp.com[Verify that the original nodes support the same software version and patch level as the new nodes^]. 

* If required, link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[Upgrade the ONTAP version on the original nodes to the maximum supported version^].
+
NOTE: The version difference between the original and new nodes cannot be greater than four. For example, ONTAP 9.8 and 9.12.1 is supported; however, ONTAP 9.8 and 9.13.1 is NOT supported. 
+
For details on mixed software version cluster upgrades, see https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html[Mixed version ONTAP clusters^].
|Do my systems contain internal drives?

Am I moving volumes?

a|* link:upgrade-by-moving-volumes-parent.html[Upgrade by moving volumes] (a nondisruptive procedure)

* link:https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html[Verify that the new nodes have enough storage to accommodate storage associated with the original nodes^].
* When you upgrade by moving volumes, new nodes are joined to the cluster before the original nodes are removed.
+
https://hwu.netapp.com[Verify that the number of controllers in the cluster does not exceed the supported maximum cluster size during the procedure^].
+
You must observe the maximum cluster size. 
+
NOTE: You must reestablish the Service Level Manager reporting nodes for SAN 8-node clusters going to an ONTAP version that supports 12-nodes.

|Am I moving internal storage or converting the system to a drive shelf?
a|* link:upgrade-by-moving-storage-parent.html[Upgrade by moving storage] (a disruptive procedure)
* https://hwu.netapp.com/[Verify that the root aggregate size and the number of disks supported by the new system are equal to or greater than those supported by the original system^].

NOTE: You can upgrade by moving storage from one FAS2xxx to a later FAS2xxx if the nodes are in the same cluster. For example, you can move volumes or physical storage from a FAS2620 to a FAS2820.



|Am I combining different controller platform models in a cluster?

a|link:https://hwu.netapp.com[Verify that you are following storage platform mixing rules^].

The controllers in a HA pair must be two AFF, FAS, or ASA models.

|Am I upgrading a HA pair in a cluster with multiple HA pairs? 
|Move epsilon to the node of a HA pair not undergoing a controller upgrade. For example, if you are upgrading nodeA/nodeB in a cluster with the HA pair configuration nodeA/nodeB and nodeC/nodeD, you must move epsilon to nodeC or nodeD.
|Am I running ONTAP 9.6P11, 9.7P8, or later releases? 
|NetApp recommends that you enable Connectivity, Liveliness, and Availability Monitor (CLAM) takeover to return the cluster into quorum when certain node failures occur. The `kernel-service` command requires advanced privilege level access. For more information, see the NetApp Knowledge Base article https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436[CLAM takeover default configuration changed^]. 

Beginning with ONTAP 9.8, the `kcs-enable-takeover` parameter is enabled by default.
|===

== Systems with internal storage

NOTE: The following systems have internal storage: FAS2520, FAS2552, FAS2554, FAS2620, FAS2650, FAS2720, FAS2750, AFF A150, AFF A200, AFF A220, AFF A250, AFF A700s, AFF A800, AFF C190, AFF C250, and AFF C800.

* If your system is not listed above, see the https://hwu.netapp.com[NetApp Hardware Universe^] to check if it has internal drives.
* If you have a system with internal storage, you can convert the system to a drive shelf and attach it to a new node in the same cluster. FAS2520 controllers cannot be converted to a drive shelf.
+
Converting a FAS255x system to a drive shelf is an optional task in the workflow for upgrading by moving storage.

* If you have a system with internal storage or a system with volumes or aggregates on internal SATA drives or SSDs, you can upgrade by transferring the internal storage to a drive shelf that is attached to the new node in the same cluster.
+
Transferring the internal storage is an optional task in the workflow for upgrading by moving storage.

== Situations where you might need additional steps

* If you are upgrading from an AFF A250 to an AFF A400, see xref:upgrade_aff_a250_to_aff_a400_ndu_upgrade_workflow.adoc[Upgrade AFF A250 to AFF A400 by converting to a drive shelf].

* If the new system has fewer slots than the original system, or if it has fewer or different types of ports, you might need to add an adapter to the new system.
+
https://hwu.netapp.com[NetApp Hardware Universe^]

* If the original nodes or new nodes use FlexArray Virtualization software.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/V_Series/What_are_the_specific_steps_involved_in_FlexArray_for_NetApp_controller_upgrades%2F%2Freplacements%3F[NetApp KB Article: What are the specific steps involved in FlexArray for NetApp controller upgrades and replacements^]

* If your cluster has SAN hosts you might need to take steps to resolve issues with LUN serial number changes.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FlexPod_with_Infrastructure_Automation/resolve_issues_during_storage_controller_motherboard_replacement_and_head_upgrades_with_iSCSI_and_FCP[How to resolve issues during storage controller motherboard replacement and head upgrades with iSCSI and FCP^]

* If your system uses out-of-band ACP, you might need to migrate from out-of-band ACP to in-band ACP.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/In-Band_ACP_Setup_and_Support[NetApp KB Article: In-Band ACP Setup and Support^]

*Related information*

* link:choose_controller_upgrade_procedure.html[Choose methods for upgrading controller hardware]
* xref:upgrade-by-moving-storage-parent.adoc[Upgrade controller hardware by moving storage]
* xref:upgrade-by-moving-volumes-parent.adoc[Upgrade controller hardware by moving volumes]

// 2023 JULY 3, BURTs 1552420, 1552651, and 1552660
// 2023 JUN 7, AFFFASDOC-46
// 2023 MAR 23, ontap-systems-upgrade-issue-82
// 2023 MAR 23, BURT 1541393
// 2023 Feb 1, BURT 1351102
// 2022 SEP 3, Clean-up 
// 2022 FEB 9, BURT 1493415 
// 2022 JAN 31, BURT 1400769

