---
permalink: upgrade/upgrade-move-lifs-to-new-nodes.html
sidebar: sidebar
keywords: move, volume, original, node, migrate, non-san, lif, cluster-management, move non-san data lifs and cluster management lifs to the new nodeas
summary: After you have moved the volumes from the original nodes, you need to migrate the non-SAN data LIFs and cluster-management LIFs from the original nodes to the new nodes.
---
= Move non-SAN data LIFs and cluster management LIFs to the new nodes
:icons: font
:imagesdir: ../media/

[.lead]
After you have moved the volumes from the original nodes, you must migrate the non-SAN data LIFs and cluster-management LIFs from the original nodes to the new nodes.

.About this task
You cannot migrate a LIF that is used for copy-offload operations with VMware vStorage APIs for Array Integration (VAAI).

.Steps
. From the node where the cluster LIF is hosted, change the home ports for the non-SAN data LIFs from the original nodes to the new nodes:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -home-node _new_node_name_ -home-port {<netport|ifgrp>}`
. Take one of the following actions:
+
[options="header" cols="1,2"]
|===
| If you want to migrate...| Then enter...

a|
A specific LIF
a|
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _dest_node_name_ -destination-port _dest_port_name_`
a|
All the non-SAN data LIFs and cluster-management LIFs
a|
`network interface migrate-all -node _node_name_`
|===
The following command migrates a LIF named "datalif1" on the SVM "vs0" to the port "e0d" on "node0b":
+
----
cluster::> network interface migrate -vserver vs0 -lif datalif1 -destination-node node0b -destination-port e0d
----
+
The following command migrates all the data and cluster-management LIFs from the current (local) node:
+
----
cluster::> network interface migrate-all -node local
----

. Check whether the home node of the cluster-management LIF is on one of the original nodes: `network interface show -lif cluster_mgmt -fields home-node`
. If the home node of the cluster management LIF is on one of the original nodes, complete the following steps:
.. Switch the home node of the cluster-management LIF to one of the new nodes:
+
`network interface modify -vserver _cluster_name_ -lif cluster_mgmt -home-node _new_node_name_ -home-port {<netport|ifgrp>}`
.. Migrate the cluster-management LIF to one of the new nodes:
+
`network interface migrate -vserver _vserver_name_ -lif cluster-mgmt -destination-node _new_node_name_ -destination-port {<netport|ifgrp>}`

// 2023 JUN 15, BURT 1552668
// 2022 MAY13, BURT 1476241
// 2022 MAR 9, Clean-up
