---
permalink: upgrade/upgrade-move-lifs-to-new-nodes.html
sidebar: sidebar
keywords: move, volume, original, node, migrate, non-san, lif, cluster-management, move non-san data lifs and cluster management lifs to the new nodeas
summary: After you have moved the volumes from the original nodes, you need to migrate the non-SAN data LIFs and cluster-management LIFs from the original nodes to the new nodes.
---
= Move non-SAN data LIFs and cluster-management LIFs to the new nodes
:icons: font
:imagesdir: ../media/

[.lead]
After you have moved the volumes from the original nodes, you must migrate the non-SAN data LIFs and cluster-management LIFs from the original nodes to the new nodes.

.About this task
You cannot migrate a LIF that is used for copy-offload operations with VMware vStorage APIs for Array Integration (VAAI).

.Steps
. Log in with the cluster-management LIF, and list all LIFs on the original nodes (comma-separated list):
+
[source,cli]
----
network interface show -curr-node <list_of_original_node_names>
----
. Change the home ports for the non-SAN data LIFs from the original nodes to the new nodes:
+
[source,cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
. Take one of the following actions:
+
[options="header" cols="1,2"]
|===
| If you want to migrate...| Then enter...

a|
A specific LIF
a|
[source,cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <dest_node_name> -destination-port <dest_port_name>
----
a|
All the non-SAN data LIFs and cluster-management LIFs
a|
[source,cli]
----
network interface migrate-all -node <node_name>
----
|===
The following command migrates a LIF named "datalif1" on the SVM "vs0" to the port "e0d" on "node0b":
+
[source,cli]
----
cluster::> network interface migrate -vserver vs0 -lif datalif1 -destination-node node0b -destination-port e0d
----
+
The following command migrates all the data and cluster-management LIFs from the current (local) node:
+
[source,cli]
----
cluster::> network interface migrate-all -node local
----

. Check whether the home node of the cluster-management LIF is on one of the original nodes:
+
[source,cli]
----
network interface show -lif cluster_mgmt -fields home-node
----
. If the home node of the cluster management LIF is on one of the original nodes, complete the following steps:
.. Switch the home node of the cluster-management LIF to one of the new nodes:
+
[source,cli]
----
network interface modify -vserver <cluster_name> -lif cluster_mgmt -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
.. Migrate the cluster-management LIF to one of the new nodes:
+
[source,cli]
----
network interface migrate -vserver <vserver_name> -lif cluster-mgmt -destination-node <new_node_name> -destination-port {<netport|ifgrp>}
----

// 2023 NOV 16, AFFFASDOC-93
// 2023 JUN 15, BURT 1552668
// 2022 MAY13, BURT 1476241
// 2022 MAR 9, Clean-up
