---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html
sidebar: sidebar
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs
summary: Migrate the logical interfaces (LIFs) and data aggregates on node2 to node1.
---
= Migrate LIFs and data aggregates on node2 to node1
:icons: font
:imagesdir: ../media/

[.lead]
Before converting AFF A250 node2 to a drive shelf, you migrate the logical interfaces (LIFs) and data aggregates on node2 to node1.

.Before you begin
Verify that you meet the following requirements:

* The AFF A250 and AFF A400 controllers are running the same ONTAP release and patch version.
+
[NOTE]
====
* You must netboot and install the ONTAP version on each AFF A400 that is identical to the version running on the AFF A250.
* Both the primary and backup boot image of each AFF A400 must have the same ONTAP version.
* If the AFF A400 clusters were previously configured, you must clear any residual cluster configuration by performing a `wipeconfig` from the boot menu.
====

* Both AFF A400 controllers are on standby at the LOADER prompt.
* You have all the appropriate cabling on-hand.

.About this task
The following steps are performed on AFF A250 node1.

.Steps
. Access the advanced privilege level:
+
`set -privilege advanced`

. Disable storage failover automatic giveback:
+
`storage failover modify -node _node1_ -auto-giveback false`
. Disable auto-revert of the LIFs across both nodes of the HA pair:
+
`network interface modify -lif * -auto-revert false`  
. Display the status of all data network LIFs:
+
`network interface show -role data`
. Display the status of the cluster management LIFs:
+
`network interface show -role cluster_mgmt`
. Migrate all data LIFs from the storage virtual machines hosted on node2:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node1_ -destination-port _port_name_`
+
NOTE: This command only migrates non-SAN LIFs. You cannot use it to migrate iSCSI and FCP LIFs.
. Display the status of all data LIFs in the cluster:
+
`network interface show -role data`
. If any LIFs are down, set the administrative status of the LIFs to `up` by entering the following command, once for each LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`
. Display the status of all data aggregates in the cluster:
+
`storage aggregate show` 
. Display failover eligibility:
+
`storage failover show`
. Migrate the data aggregates on node2 to node1:
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`   
. Display the status of all data aggregates in the cluster:
+
`storage aggregate show`
. Display the status of all data volumes in the cluster:
+
`volume show` 
. Display the `ha` status and ownership of epsilon:
+
`cluster show` 
. Disable `cluster ha`:
+
`cluster ha modify -configured false` 
. Display the `ha` status and ownership of epsilon:
+
`cluster show` 
. Halt node2:
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`   

.What's next?

link:upgrade_convert_node2_drive_shelf_connect_node4.html[Convert node2 to a drive shelf and connect to node4]

// 2023 JUN 7, AFFFASDOC-46
// 2023 Feb 1, BURT 1351102