---
permalink: upgrade/upgrade-optional-move-internal-storage.html
sidebar: sidebar
keywords: node, support, model, internal, sata, drive, ssd, moving, move, upgrading, upgrade, convert, move internal storage or convert the system to a drive shelf
summary: If your original node is one of the supported models, you have the option to move its internal SATA drives, SSDs, or SAS drives to a drive shelf that is attached to the new nodes during the process of upgrading by moving storage. You can also convert the system to a drive shelf and attach it to the new nodes.
---
= Overview
:icons: font
:imagesdir: ../media/

[.lead]
If your original node is one of the supported models, you have the option to move its internal SATA drives, SSDs, or SAS drives to a drive shelf that is attached to the new nodes during the process of upgrading by moving storage. You can also convert the system to a drive shelf and attach it to the new nodes.

.About this task
You can move drives or drive shelves only within the same cluster.

.Choices
* link:upgrade-move-internal-drives.html[Move internal drives from an original node]
+
If your original node is one of the supported models, during the process of upgrading by moving
storage you can move the node's internal SATA drives, SSDs, or SAS drives to a drive shelf that is attached to
the new node in the same cluster.

* link:upgrade-convert-node-to-shelf.html[Convert an original node to a drive shelf]
+
If your original node is one of the supported models, during the process of upgrading by moving
storage you can convert the node to a drive shelf and then attach it to the new nodes in the same
cluster..

// 2022 SEP 29, BURT 1504117