---
sidebar: sidebar
permalink: upgrade-arl-auto/get_ip_address_of_external_kms_for_storage_encryption.html
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management
summary: "Configure and manage Storage Encryption, manage authentication keys, and quiesce the SnapMirror relationships when upgrading controllers running ONTAP 9.5 to 9.7 by using `system controller replace` commands."
---

= Get an IP address of an external key management server for storage encryption
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After upgrading, you must immediately configure Storage Encryption and establish a cluster-wide authentication key to replace the previous node-level authentication keys.

.Steps

. Install the necessary client and server secure sockets layer (SSL) certificates required to communicate with key management servers:
+
`security certificate install`

. Configure Storage Encryption on all nodes by using the following command on each node:
+
`security key-manager setup`

. Add the IP address for each key management server:
+
`security key-manager add`

. Verify that the same key management servers are configured and available on all nodes in the cluster:
+
`security key-manager show -status`

. Create a new cluster-wide authentication key:
+
`security key-manager create-key`

. Make a note of the new authentication key ID.
. Rekey all self-encrypting drives with the new authentication key:
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`

== Manage authentication using KMIP servers

With ONTAP 9.5 to 9.7, you can use Key Management Interoperability Protocol (KMIP) servers to manage authentication keys.

Steps

. Add a new controller:
+
`security key-manager setup -node _new_controller_name_`

. Add the key manager:
+
`security key-manager -add _key_management_server_ip_address_`

. Verify that the key management servers are configured and available to all nodes in the cluster:
+
`security key-manager show -status`

. Restore the authentication keys from all linked key management servers to the new node:
+
`security key-manager restore -node _new_controller_name_`

. Rekey all self-encrypting disks with the new authentication key:
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK]`

. If you use the Federal Information Processing Standard (FIPS), rekey all self-encrypting disks with the new authentication key:
+
`storage encryption disk modify -disk * [-fips-key-id nonMSID AK]`

// p. 20 of PDF-- include subheadings
// BURT 1476241 2022-05-13
// BURT-1476241 2022-August-12
