---
sidebar: sidebar
permalink: upgrade-arl-auto/get_ip_address_of_external_kms_for_storage_encryption.html
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management
summary: Configure Storage Encryption and establish a cluster-wide authentication key to replace the previous node-level authentication keys
---

= Get an IP address of an external key management server for storage encryption
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After upgrading, you must immediately configure Storage Encryption and establish a cluster-wide authentication key to replace the previous node-level authentication keys.

.Steps

. Install the necessary client and server secure sockets layer (SSL) certificates required to communicate with key management servers:
+
`security certificate install`

. Configure Storage Encryption on all nodes by using the following command on each node:
+
`security key-manager setup`

. Add the IP address for each key management server:
+
`security key-manager add`

. Verify that the same key management servers are configured and available on all nodes in the cluster:
+
`security key-manager show -status`

. Create a new cluster-wide authentication key:
+
`security key-manager create-key`

. Make a note of the new authentication key ID.
. Rekey all self-encrypting drives with the new authentication key:
+
`storage encryption disk modify -disk * -data-key-id <authentication_key_id>`


== Manage authentication using KMIP servers

With ONTAP 9.5 to 9.7, you can use Key Management Interoperability Protocol (KMIP) servers to manage authentication keys.

Steps

. Add a new controller:
+
`security key-manager setup -node <new_controller_name>`

. Add the key manager:
+
`security key-manager -add <key_management_server_ip_address>`

. Verify that the key management servers are configured and available to all nodes in the cluster:
+
`security key-manager show -status`

. Restore the authentication keys from all linked key management servers to the new node:
+
`security key-manager restore -node <new_controller_name>`

. Rekey all self-encrypting disks with the new authentication key:
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK]`

. If you use the Federal Information Processing Standard (FIPS), rekey all self-encrypting disks with the new authentication key:
+
`storage encryption disk modify -disk * [-fips-key-id nonMSID AK]`

== Manage storage encryption using Onboard Key Manager

You can use the OKM to manage encryption keys. If you plan to use OKM, you must record the passphrase and backup material before beginning the upgrade.

.Steps

. Save the passphrase to a secure location.
. Create a backup for recovery purposes. Run the following command and save the output:
+
`key-manager onboard show-backup`

include::../_include/ru_auto_manage_storage_encryption_okm.adoc[]

include::../_include/ru_auto_quiesce_snapmirror_relationships.adoc[]

// p. 20 of PDF-- include subheadings
