If the replaced controller or high availability (HA) partner of the new controller uses NetApp Volume Encryption (NVE), you must configure the new controller module for NVE.

.About this task

This procedure includes steps that are performed on the new controller module. You must enter the command on the correct node.

[role="tabbed-block"]
====
.Onboard Key Manager
--
*If you are using Onboard Key Manager, perform the following procedure:*

. Restore authentication keys from all linked key management servers to the new node:
+
`security key-manager onboard sync`
--

.External Key Management 
--
*If you are using External Key Management, perform the following procedure:*

. Verify that the key management servers are still available, their status, and their authentication key information:
+
`security key-manager key query -node node`

. Add the key management servers listed in the previous step to the key management server list in the new controller:
.. Add the key management server:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`
// BURT 1450483 11-Feb 2022
.. Repeat the previous step for each listed key management server. You can link up to four key management servers.
.. Verify the that the key management servers were added successfully:
+
`security key-manager external show`
// BURT 1450483 11-Feb 2022
. On the new controller module, run the key management setup wizard to set up and install the key management servers.
+
You must install the same key management servers that are installed on the existing controller module.

.. Launch the key management server setup wizard on the new node:
+
`security key-manager external enable`
// BURT 1450483 11-Feb 2022
.. Complete the steps in the wizard to configure key management servers.
. Restore authentication keys from all linked key management servers to the new node:
+
`security key-manager external restore`
+
This command needs the OKM passphrase
--
====

.After you finish
Check if any volumes were taken offline because authentication keys were not available or EKM servers could not be reached. Bring those volumes back online by using the `volume online` command.
