. Add the FC initiator ports to the storage array as new hosts, mapping the array LUNs to the new hosts.
+
See your storage array and zoning documentation for instructions.

. Modify the worldwide port name (WWPN) values in the host or volume groups associated with array LUNs on the storage array.
+
Installing a new controller module changes the WWPN values associated with each onboard FC port.

. If your configuration uses switch-based zoning, adjust the zoning to reflect the new WWPN values.

. [[step27]]Set the `bootarg.storageencryption.support` and `kmip.init.maxwait` variables to avoid a boot loop after the node2 configuration is loaded.
+
If you have not already done so earlier in the procedure, determine the type of self-encrypting drives that are in use:
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed[NetApp KB Article: How to tell I have FIPS drives installed^]
+
[cols="35,65"]
|===
|If the following drives are in use…	|Then…

|NetApp Storage Encryption (NSE) drives that conform to FIPS 140-2 Level 2 self-encryption requirements
a|* `setenv bootarg.storageencryption.support *true*`

* `setenv kmip.init.maxwait off`

|NetApp non-FIPS SEDs
a|* `setenv bootarg.storageencryption.support *false*`

* `setenv kmip.init.maxwait off`
|===
+
[NOTE]
====
* You cannot mix FIPS drives with other types of drives on the same node or HA pair.
* You can mix SEDs with non-encrypting drives on the same node or HA pair.
* If a power outage occurs after you set the `kmip.init.maxwait` variable to `off`, contact technical support for assistance to avoid potential data loss.

* As soon as the controller upgrade completes on the HA pair, you must unset the `kmip.init.maxwait` variable. See link:ensure_new_controllers_are_set_up_correctly.html[Confirm that the new controllers are set up correctly].
====

. Boot node into boot menu:
+
`boot_ontap menu`
+
If you do not have an FC or UTA/UTA2 configuration, execute link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15[Check and configure UTA/UTA2 ports on node4, Step 15] so that node4 can recognize node2’s disks.
