---
sidebar: sidebar
permalink: upgrade-arl-manual/ensure_controllers_set_up_correctly.html
keywords: set up, controllers, correctly, ha pair, lif, aggregate, node, failover
summary: "Enable the HA pair, verify node3 and node4 storage access, and confirm aggregate ownership after a manual ARL upgrade on controllers running ONTAP 9.7 or earlier."
---

= Confirm that the new controllers are set up correctly
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::../_include/ru_man_ensure_controllers_set_up_correctly.adoc[]
[start=14]
. Take the following actions on one of the new nodes:
.. Enter advanced privilege level by entering the following command:
+
`set -privilege advanced`
.. Enter the following command:
+
`storage failover modify -node _node-name_ -cifs-ndo-duration default|medium|low`
+
* Enter `medium` if the system will have workloads in which 50 percent to 75 percent of the operations will be 4 KB or smaller.
* Enter `low` if the system will have workloads in which 75 percent to 100 percent of the operations will be 4 KB or smaller.
.. Return to the admin level by entering the following command:
+
`set -privilege admin`
.. Reboot the system to confirm that the changes take effect.

. If you want to set up a switchless cluster on the new nodes, go to link:other_references.html[References] to link to the _Network Support Site_ and follow the instructions in _Transitioning to a two-node switchless cluster_.

.After you finish

If Storage Encryption is enabled on node3 and node4, complete the steps in link:set_up_storage_encryption_new_controller.html[Set up Storage Encryption on the new controller module]. Otherwise, complete the steps in link:decommission_old_system.html[Decommission the old system].
// 25 Feb 2021:  formatted from CMS
// BURT 1489176, 2022-08-02
