---
sidebar: sidebar
permalink: upgrade-arl-manual/index.html
keywords:  controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster
summary: You upgrade the original controller hardware with the replacement controller hardware, relocating the ownership of non-root aggregates.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This procedure describes how to upgrade the controller hardware using aggregate relocation (ARL) for the following system configurations:

[cols=3*,options="header",cols="20,20,60"]
|===
|Method |ONTAP version |Supported systems

|Manual upgrade
|9.7 or earlier
a|* FAS system to FAS system
* FAS system to V-Series system or system with FlexArray Virtualization Software
* V-Series system to V-Series system or a system with FlexArray Virtualization Software
* V-Series system or system with FlexArray Virtualization Software to an FAS system, provided that the V-Series system or system with FlexArray Virtualization Software has no array LUNs.
* AFF system to AFF system
|===

include::../_include/ru_man_use_arl_overview.adoc[]

* This procedure applies to MetroCluster four-node and eight-node configurations running ONTAP 9.5 and earlier. For MetroCluster configurations running ONTAP 9.6 and later, go to link:other_references.html[References] to link to _Using “system controller replace” Commands to Upgrade Controller Hardware Running ONTAP 9.5 to ONTAP 9.7_.


// 24 FEB 2021:  formatted from CMS
