---
sidebar: sidebar
permalink: upgrade-arl-manual/install_boot_node4.html
keywords: node4, install ONTAP, boot, node4, relocate, non-root aggregates, disks
summary: "Install and boot node4 and install ONTAP software during a manual ARL upgrade on controllers running ONTAP 9.7 or earlier."
---

= Install and boot node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::../_include/ru_man_install_boot_node4_intro_to_step_15.adoc[]
. If you have NetApp Storage Encryption (NSE) drives installed, preform the following steps.
+
NOTE: If you have not already done so earlier in the procedure, see the Knowledge Base article https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed[How to tell I have FIPS drives installed^] to determine the type of self-encrypting drives that are in use.
+
.. Set the `bootarg.storageencryption.support` variable:
+ 
[cols="35,65"]
|===
|If the following drives are in use…	|Then…
|NSE drives that conform to FIPS 140-2 Level 2 self-encryption requirements
|`setenv bootarg.storageencryption.support *true*`
|NetApp non-FIPS SEDs
|`setenv bootarg.storageencryption.support *false*`
|===
+
[NOTE]
====
You cannot mix FIPS drives with other types of drives on the same node or HA pair.

You can mix SEDs with non-encrypting drives on the same node or HA pair.
====
+
Contact NetApp Support for assistance with restoring the onboard key management information.

include::../_include/ru_man_install_boot_node4_steps_17_to_48.adoc[]
