---
sidebar: sidebar
permalink: upgrade-arl-auto-app/install_boot_node3.html
keywords: installing, booting, node3, ontap
summary: "Install and boot node3 and install ONTAP software when upgrading controllers running ONTAP 9.8 or later by using `system controller replace` commands."
---

= Install and boot node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:54.146306
//

[.lead]
include::../_include/ru_auto_install_boot_node3_intro_step_5.adoc[]

[start=6]
. [[step6]]Configure the netboot connection by choosing one of the following actions.
+
NOTE: You must use the management port and IP as the netboot connection. Do not use a data LIF IP or a data outage might occur while the upgrade is being performed.

+
[cols=2*,options="header"cols="30,70"]
|===
|If Dynamic Host Configuration Protocol (DHCP) is... |Then...

|Running
|Configure the connection automatically by using the following command at the boot environment prompt:
`ifconfig e0M -auto`
|Not running
a|Manually configure the connection by using the following command at the boot environment prompt:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` is the IP address of the storage system (mandatory).
`_netmask_` is the network mask of the storage system (mandatory).
`_gateway_` is the gateway for the storage system (mandatory).
`_dns_addr_` is the IP address of a name server on your network (optional).
`_dns_domain_` is the Domain Name Service (DNS) domain name (optional).

NOTE: Other parameters might be necessary for your interface. Enter `help ifconfig` at the firmware prompt for details.
|===

include::../_include/ru_auto_install_boot_node3_step_7_28.adoc[]

[start=29]
. [[step29]]For a MetroCluster configuration, V-Series systems and systems with FlexArray Virtualization software connected to storage arrays,  you must set and configure the FC or UTA/UTA2 ports on node3 to detect the disks attached to the node.
To complete this task, go to section link:set_fc_or_uta_uta2_config_on_node3.html[Set the FC or UTA/UTA2 configuration on node3].

// 2022-05-17, BURT 1476241
