---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900
summary: "Decide whether to use the ARL procedure to upgrade an AFF A700 to an AFF A900."
---

= Decide whether to use the aggregate relocation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This content describes how to upgrade storage controllers in an AFF A700 HA pair with new AFF A900 controllers or controllers in a FAS9000 HA pair with new FAS9500 controllers, while keeping all the existing data and disks. This is a complex procedure that should be used only by experienced administrators.

Use this procedure under the following circumstances:

* You have verified with your NetApp sales representative that you have received the AFF A900 or FAS9500 controller and NVRAM modules and the parts required for the upgrade.
* You are running ONTAP 9.11.1P6 or 9.10.1P10 (targeted to February 2023).
* You do not want to add the new controllers as a new HA pair to the cluster and migrate the data by using volume moves.
* You are experienced in administering ONTAP and are comfortable with the risks of working in diagnostic privilege mode.

Do *NOT* use this procedure under the following circumstances:

* You are using FlexArray Virtualization Software on the AFF A700 or FAS9000 systems.
* You are using a shared switch for cluster-interconnect and Ethernet attached storage.

For upgrading Fabric MetroCluster or MetroCluster IP configurations, see link:other_references.html[References] to link to the _MetroCluster Upgrade and Expansion_ content.

NOTE: You can use NetApp Storage Encryption (NSE) and NetApp Volume Encryption (NVE) with this procedure.

If you prefer a different method of upgrading the controller hardware and are willing to do volume moves, refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_.

Refer to link:other_references.html[References] to link to the _ONTAP 9 Documentation Center_ where you can access ONTAP 9 product documentation.

//BURT 1452254, 2022-04-26
