---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900
summary: "Decide whether to use the ARL procedure to upgrade an AFF A700 to an AFF A900."
---
= Decide whether to use the aggregate relocation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This content describes how to upgrade storage controllers in a HA pair while keeping all the existing data and disks. This is a complex procedure that should be used only by experienced administrators.

Use this procedure under the following circumstances:

* You are performing one of the following controller upgrades:
+
[cols=2*,options="header",cols="50,50"]
|===
|Old controller
|Replacement controller
|AFF A220, AFF A200, or AFF C190
|AFF A150
|FAS2620 or FAS2720
|FAS2820
|AFF A700
|AFF A900
|FAS9000
|FAS9500
|===

* You have verified with your NetApp sales representative that you have received the hardware for your controller upgrade:
** AFF A150 controller
** FAS2820 controller
** AFF A900 or FAS9500 controller and NVRAM modules and the parts required for the upgrade.

* You are running the minimum ONTAP version for your upgrade. For more information, see link:guidelines_for_upgrading_controllers_with_arl.html[Supported upgrades for ARL].
* You do not want to add the new controllers as a new HA pair to the cluster and migrate the data by using volume moves.
* You are experienced in administering ONTAP and are comfortable with the risks of working in diagnostic privilege mode.

Do *NOT* use this procedure under the following circumstances:

* You are using FlexArray Virtualization Software on the AFF A700 or FAS9000 systems.
* You are using a shared switch for cluster-interconnect and Ethernet attached storage.

For upgrading Fabric MetroCluster or MetroCluster IP configurations on AFF A700 or FAS9000 systems, see link:other_references.html[References] to link to the _MetroCluster Upgrade and Expansion_ content.

NOTE: You can use NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE), and NetApp Aggregate Encryption (NAE) with this procedure.

If you prefer a different method of upgrading the controller hardware and are willing to do volume moves, refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_.

Refer to link:other_references.html[References] to link to the _ONTAP 9 Documentation Center_ where you can access ONTAP 9 product documentation.


// 2023 MAY 29, AFFFASDOC-39
// 2022 Jan 30, BURT 1523106
// 2022 APR 26, BURT 1452254 
