---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers
summary: "Understand if you can use ARL to upgrade an AFF A700 to an AFF A900."
---
= Guidelines for upgrading controllers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To understand whether you can use aggregate relocation (ARL), keeping the old system chassis and disks, depends on the system upgrade configuration and ONTAP version.

== Supported upgrades for ARL

Controller upgrades are supported for the following system configurations.

WARNING: This procedure strictly applies to the following upgrade configurations. Do NOT use this procedure to perform an upgrade between any other system combinations.

[cols=3*,options="header",cols="20,20,40"]
|===
|Old system |Replacement system |Supported ONTAP versions
|FAS2620 
|FAS2820
|9.11.1P7 or earlier (FAS2620) 
9.13.1 or later (FAS2820)
|FAS2720 |FAS2820	
|9.13.1 or later
|AFF A700 
|AFF A900
|9.10.1P10, 9.11.1P6 or later
|FAS9000 |FAS9500
|9.10.1P10, 9.11.1P6 or later
|===

If you have received a new FAS2820, AFF A900, or FAS9500 system as a complete system, including a new chassis, refer to link:other_references.html[References] to link to the _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ content.

Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise and SnapLock Compliance volumes.

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster.

== Troubleshoot

If any problems occur while upgrading the controllers, see the link:troubleshoot_index.html[Troubleshoot] section at the end of the procedure for more information and possible solutions.

If you do not find a solution to the problem you encountered, contact technical support.

// 2023 MAY 22, BURT 1542232
// 2023 MAY 22, BURT 1531220
// 2022 Jan 30, BURT 1523106
// 2022 APR 26, BURT 1452254
