---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers
summary: "Understand if you can use ARL to upgrade an AFF A700 to an AFF A900."
---

= Guidelines for upgrading controllers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using ARL to upgrade a pair of controllers running 9.10.1P10, 9.11.1P6, or a later release in the following system configurations:

* AFF A700 controllers to an AFF A900 system
* FAS9000 controllers to a FAS9500 system

== Supported upgrades for ARL

Controller upgrade from an AFF A700 to an AFF A900 or from a FAS9000 to a FAS9500 using ARL and the NVRAM module is the supported combination. If you have received a new AFF A900 or FAS9500 system as a complete system, including a new chassis, refer to link:other_references.html[References] to link to the _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ content.

WARNING: This procedure strictly applies to an AFF A700 to AFF A900 or a FAS9000 to FAS9500 upgrade running 9.10.1P10, 9.11.1P6, or a later release. Do NOT use this procedure to perform an upgrade between any other system combinations.

Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise and SnapLock Compliance volumes.

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster.

== Troubleshoot

If any problems occur while upgrading the controllers, see the link:troubleshoot_index.html[Troubleshoot] section at the end of the procedure for more information and possible solutions.

If you do not find a solution to the problem you encountered, contact technical support.

//BURT 1452254, 2022-04-26
