---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/index.html
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900
summary: "You can upgrade controller hardware on an AFF A700 to an AFF A900 by swapping the controller module and NVS."
---
= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This procedure describes how to nondisruptively upgrade controller hardware on a HA pair using aggregate relocation (ARL) for the following system configurations. The procedure converts the old system to the replacement system keeping the old system chassis and disks. 

[cols=3*,options="header",cols="20,20,40"]
|===
|Old system |Replacement system |Supported ONTAP versions
|FAS2620 
|FAS2820
|9.11.1P7 or earlier (FAS2620) 
9.13.1 or later (FAS2820)
|FAS2720 |FAS2820	
|9.13.1 or later
|AFF A700 
|AFF A900
|9.10.1P10, 9.11.1P6 or later
|FAS9000 |FAS9500
|9.10.1P10, 9.11.1P6 or later
|===

NOTE: NetApp recommends, if possible, that you have the same ONTAP version on the old and the replacement system.

During the procedure, you migrate the non-root aggregates between the old controller nodes. After installation, you then migrate the non-root aggregates from the old controller nodes to the replacement controller nodes. The data hosted on the nodes that you are upgrading is accessible during the upgrade procedure.

.About this task
During this controller upgrade procedure, you perform one of the following procedures:

* Swap the controller module on each node on the FAS2620 or FAS2720 system with the new FAS2820 module.
* Swap the two controller and NVRAM modules on each node on the AFF A700 or FAS9000 system with the new AFF A900 or FAS9500 modules.

NOTE: You do not need to move, disconnect, or reconnect the I/O cards, data cables, disk shelves, and disks.

This procedure uses a method called aggregate relocation (ARL), which takes advantage of the HA configuration to enable you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

During the procedure, you upgrade the original controller hardware with the replacement controller hardware, relocating the ownership of non-root aggregates. You migrate aggregates multiple times from node to node to confirm that at least one node is serving data from the aggregates throughout the upgrade procedure. You also migrate data LIFs between nodes in the cluster as you proceed.

NOTE: The terms *node1* and *node2*, are used only as a reference to node names in this document. When following the procedure, you must substitute the real names of your nodes.

.Important information

* This procedure is complex and assumes that you have advanced ONTAP administration skills. You also should read and understand the link:guidelines_for_upgrading_controllers_with_arl.html[Guidelines for upgrading controllers] and the  link:overview_of_the_arl_upgrade.html[Overview of the ARL upgrade] sections before beginning the upgrade.
* This procedure assumes that the replacement controller hardware is new and has not been used in another system. The steps required to prepare used controllers with the `wipeconfig` command are not included in this procedure. You must contact technical support if the replacement controller hardware was previously used as part of another ONTAP cluster or as a standalone single node system.
* You can use this procedure to upgrade the controller hardware in clusters with more than two nodes; however, you need to perform the procedure separately for each HA pair in the cluster.
* If you have a switch that is not supported by the ONTAP version and the replacement system that you are upgrading to, refer to link:other_references.html[References] to link to the _Hardware Universe_.
* This procedure only applies FAS2620, FAS2720, AFF A700, and FAS9000 systems. For all other controller models that need upgrading to a FAS2820, AFF A900, or FAS9500 system, refer to link:other_references.html[References] to link to the _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ and the _Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.8 or Later_ content.
* The AFF A900 and FAS9500 systems only support high-line power (200V to 240V). If your AFF A700 or FAS9000 system is running on low-line power (100V to 120V), you must convert the AFF A700 or FAS9000 input power before using this procedure.
* If you are upgrading from a FAS2620, FAS2720, AFF A700, or FAS9000  ystem with downtime, you can upgrade controller hardware by moving storage or contact technical support. Refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_.

== Automate the controller upgrade process
This procedure supports the following controller upgrades and provides the steps for the automated procedure, which uses automatic disk assignment and network port reachability checks to simplify the controller upgrade experience

// 2023 MAY 22, BURT 1542232
// 2023 MAY 22, BURT 1531220
// 2022 JAN 30, BURT 1523106
// 2022 APR 26, BURT 1452254
