---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/install_replacement_system_modules_on_node2.html
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement
summary: "Install the replacement system modules on node2 during an ARL upgrade of controller models in the same chassis."
---
= Install the replacement system modules on node2
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Install the replacement system modules that you received for the upgrade on node2. Node2 is controller B located on the right side of the chassis when looking at the controllers from the rear of the system.

* <<install_modules_a,Install the ASA A150, AFF A150, or FAS2820 controller module on node2>>
* <<install_modules_b,Install the ASA A900, AFF A900, or FAS9500 NVRAM and controller modules on node2>>

[[install_modules_a]]
== Install the ASA A150, AFF A150 or FAS2820 controller module on node2
Install the ASA A150, AFF A150 or FAS2820 controller module that you received for the upgrade on node2. Node2 is controller B located on the right side of the chassis when looking at the controllers from the rear of the system.

.Before you begin

* If you are not already grounded, correctly ground yourself.
* Disconnect all the cables, including console, management, SAS storage, and data network cables, from the controller being removed.

.Steps

. Align the end of the controller module with bay B in the chassis, and then gently push the controller module halfway into the system.
+
TIP: Bay B is located on the chassis at the bottom.
+
WARNING: Do not completely insert the controller module in the chassis until you are instructed to do so later in the procedure.

. Cable the management and console ports to the node2 controller module.
+
NOTE: Because the chassis is already powered ON, node2 starts booting as soon as it is fully seated. To avoid node2 booting, NetApp recommends that you connect the console and management cables to the node2 controller module before completely inserting the controller module into the slot.

. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
The locking latch rises when the controller module is fully seated.
+
NOTE: To avoid damaging the connectors, do not use excessive force when sliding the controller module into the chassis.

. Connect the serial console as soon as the module is seated and be ready to interrupt AUTOBOOT of node1.
. After you interrupt AUTOBOOT, node2 stops at the LOADER prompt. If you do not interrupt AUTOBOOT on time and node2 starts booting, wait for the prompt and press *Ctrl-C* to go into the boot menu. After the node stops at the boot menu, use option 8 to reboot the node and interrupt the AUTOBOOT during reboot.

[[install_modules_b]]
== Install the ASA A900, AFF A900, or FAS9500 NVRAM and controller modules on node2
Install the ASA A900, AFF A900, or FAS9500 NVRAM and controller modules that you received for the upgrade on node2. Node2 is controller B located on the right side of the chassis when looking at the controllers from the rear of the system. 

You must note the following when performing the installation:

* Move all blank filler modules in slots 6-1 and 6-2 from the old NVRAM module to the new NVRAM module.
* Do NOT move the coredump device from the AFF A700 NVRAM module to the ASA A900 or AFF A900 NVRAM module.
* Move all flash cache modules installed in the FAS9000 NVRAM module to the FAS9500 NVRAM module.

.Before you begin
If you are not already grounded, correctly ground yourself.

=== Install the ASA A900, AFF A900, or FAS9500 NVRAM module
Use the following procedure to install the ASA A900, AFF A900, or FAS9500 NVRAM module in slot 6 of node2.

.Steps
. Align the NVRAM module with the edges of the chassis opening in slot 6.
. Gently slide the NVRAM module into the slot until the lettered and numbered I/O cam latch begins to engage with the I/O cam pin, and then push the I/O cam latch all the way up to lock the NVRAM module in place.

=== Install the ASA A900, AFF A900, or FAS9500 controller module in node2
Use the following procedure to install the ASA A900, AFF A900, or FAS9500 controller module in node2.

.Steps
.	Align the end of the controller module with bay B in the chassis, and then gently push the controller module halfway into the system.
+
TIP:  The bay label is located on the chassis directly above the controller module.
+
NOTE: Do not completely insert the controller module in the chassis until you are instructed to do so later in the procedure.

.	Cable the management and console ports to the node2 controller module.
+
NOTE: Because the chassis is already powered ON, node2 starts booting as soon as it is fully seated. To avoid node2 booting, it is recommended that you connect the console and management cables to the node2 controller module before completely inserting the controller module into the slot.

.	Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
The locking latch rises when the controller module is fully seated.
+
WARNING: To avoid damaging the connectors, do not use excessive force when sliding the controller module into the chassis.

.	Connect the serial console as soon as the module is seated and be ready to interrupt AUTOBOOT of node1.
.	After you interrupt AUTOBOOT, node2 stops at the LOADER prompt. If you do not interrupt AUTOBOOT on time and node2 starts booting, wait for the prompt and press *Ctrl-C* to go into the boot menu. After the node stops at the boot menu, use option `8` to reboot the node and interrupt the AUTOBOOT during reboot.

.	At the LOADER> prompt of node2, set the default environment variables:
+
`set-defaults`
.	Save the default environment variables settings:
+
`saveenv`

// 2023 AUG 29, AFFFASDOC-78
// 2023 MAY 29, AFFFASDOC-39
// 2023-MAR-3, ontap-systems-upgrade/issues/78
// 2022-OCT-24, BURT 1506458 
// 2022-APR-27, BURT 1452254
