---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html
keywords: overview, arl, upgrade, owner, controller, hardware
summary: "Understand how the AFF A700 to AFF A900 ARL controller upgrade procedure works."
---

= Overview of the ARL upgrade
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::../_include/ru_auto_overview_arl_workflow_top.adoc[]

[cols="35,65"]
|===
| Stage | Steps

| link:stage_1_index.html[Stage 1: Prepare for upgrade]
a| During Stage 2, you relocate node1 non-root aggregates and NAS data LIFs to node2. This process is largely automated; the operation pauses to enable you to check its status. You must manually resume the operation. If required, you relocate failed or vetoed aggregates. You must record the necessary node1 information for use later in the procedure and then swap the corresponding node1 controller and NVRAM modules, retire node1, and netboot the upgraded node1.

Aggregate ownership at the end of Stage 1:

* Node1 is the home owner and current owner of the node1 aggregates
* Node2 is the home owner and current owner of the node2 aggregates

| link:stage_2_index.html[Stage 2: Relocate resources from node1 and retire AFF A700 or FAS9000 node1]
a| During Stage 2, you relocate node1 non-root aggregates and NAS data LIFs to node2. This process is largely automated; the operation pauses to enable you to check its status. You must manually resume the operation. If required, you relocate failed or vetoed aggregates. You record node1 information for use later in the procedure before retiring node1. You can also prepare to netboot node1 later in the procedure.

Aggregate ownership at the end of Stage 2:

* Node2 is the current owner of node1 aggregates
* Node2 is the home owner and current owner of node2 aggregates

| link:stage_3_index.html[Stage 3: Boot node1 with the replacement system modules]
a| During Stage 3, you boot node1 with upgraded controller and NVRAM modules and verify the upgraded node1 installation. If you are using NetApp Volume Encryption (NVE), you restore key-manager configuration. You also relocate node1 non-root aggregates and NAS data LIFs from node2 to the upgraded node1 and verify that the SAN LIFs exist on node1.

Aggregate ownership at the end of Stage 3:

* Upgraded AFF A900 or FAS9500 node1 is the home owner and current owner of node1 aggregates
* Node2 is the home owner and current owner of node2 aggregates

| link:stage_4_index.html[Stage 4: Relocate resources from node2 and retire node2]
a| During Stage 4, you relocate non-root aggregates and NAS data LIFs from node2 to the upgraded node1 and retire node2.

Aggregate ownership at the end of Stage 4:

*	Upgraded node1 is the home owner and current owner of aggregates that originally belonged to node1
*	Upgraded node1 is the current owner of node2 aggregates

| link:stage_5_index.html[Stage 5: Install the AFF A900 or FAS9500 NVRAM and controller modules on node2]
a| During Stage 5, you install the new NVRAM and controller modules that you received for the upgraded node2 and then netboot node2.

Aggregate ownership at the end of Stage 5:

*	Upgraded node1 is the home owner and current owner of the aggregates that originally belonged to node1.
*	Upgraded node2 is the home owner and current owner of aggregates that originally belonged to node2.

| link:stage_6_index.html[Stage 6: Boot node2 with the replacement system modules]
a| During Stage 6, you boot node2 with upgraded controller and NVRAM modules and verify the upgraded node2 installation. If you are using NVE, you restore key-manager configuration. You also relocate node1 non-root aggregates and NAS data LIFs from node1 to the upgraded node2 and verify that the SAN LIFs exist on node2.

| link:stage_7_index.html[Stage 7: Complete the upgrade]
a| During Stage 7, you confirm that the new nodes are set up correctly and, if the new nodes are encryption-enabled, you configure and set up Storage Encryption or NVE. You should also decommission the old nodes and resume the SnapMirror operations.
|===

//BURT 1452254, 2022-04-26
