---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_2_index.html
keywords: upgrade, preparing, preparation, prepare, overview, stage 1
summary: "Stage 2 process sequence for an ARL upgrade using `system controller replace` commands on controllers running ONTAP 9.8 or later."
---

= Stage 2. Relocate resources from node1 and retire AFF A700 or FAS9000 node1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
During Stage 2, you relocate node1 non-root aggregates and NAS data LIFs to node2. This process is largely automated; the operation pauses to enable you to check its status. You must manually resume the operation. If required, you relocate failed or vetoed aggregates. You record node1 information for use later in the procedure before swapping the corresponding node1 controller and NVRAM modules, retiring node1, and netbooting the upgraded node1.

.Steps

. link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2]
. link:relocate_failed_or_vetoed_aggr.html[Relocate failed or vetoed aggregates]
. link:retire_node1.html[Retire node1]
. link:netboot_node1.html[Netboot]
//BURT-1476241 13-Sep-2022
