---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_6_index.html
keywords: upgrade, preparing, preparation, prepare, overview, stage 1
summary: "Stage 1 process sequence for an ARL upgrade using `system controller replace` commands on controllers running ONTAP 9.8 or later."
---

= Stage 6. Boot node2 with the replacement system modules
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
During Stage 6, you boot node2 with upgraded controller and NVRAM modules and verify the upgraded node2 installation. If you are using NetApp Volume Encryption (NVE), you restore key-manager configuration. You also relocate node1 non-root aggregates and NAS data LIFs from node1 to the upgraded node2 and verify that the SAN LIFs exist on node2.

. link:boot_node2_with_a900_controller_and_nvs.html[Boot node2 with the replacement system modules]
. link:verify_node2_installation.html[Verify the node2 installation]
. link:restore_key_manager_config_node2.html[Restore key-manager configuration on node2]
. link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html[Move non-root aggregates and NAS data LIFs back to node2]
//BURT-1476241 13-Sep-2022
