---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_3_index.html
keywords: upgrade, preparing, preparation, prepare, overview, stage 1
summary: "Stage 1 process sequence for an ARL upgrade using `system controller replace` commands on controllers running ONTAP 9.8 or later."
---

= Stage 3. Boot node1 with the replacement system modules
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
During Stage 3, you boot node1 with upgraded controller and NVRAM modules and verify the upgraded node1 installation. If you are using NetApp Volume Encryption (NVE), you restore key-manager configuration. You also relocate node1 non-root aggregates and NAS data LIFs from node2 to the upgraded node1 and verify that the SAN LIFs exist on node1.

.Steps

. link:boot_node1_with_a900_controller_and_nvs.html[Boot node1 with the replacement system modules]
. link:verify_node1_installation.html[Verify the node1 installation]
. link:restore_key_manager_config_upgraded_node1.html[Restore key-manager configuration on the upgraded node1]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html[Move non-root aggregates and NAS data LIFs owned by node1 from node2 to the upgraded node1]
//BURT-1476241 13-Sep-2022
