---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_7_index.html
keywords: upgrade, preparing, preparation, prepare, overview, stage 1
summary: "Stage 1 process sequence for an ARL upgrade using `system controller replace` commands on controllers running ONTAP 9.8 or later."
---

= Stage 7. Complete the upgrade
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
During Stage 7, you confirm that the new nodes are set up correctly and, if the new nodes are encryption-enabled, you configure and set up Storage Encryption or NetApp Volume Encryption. You should also decommission the old nodes and resume the SnapMirror operations.

.Steps

. link:get_ip_address_of_external_kms_for_storage_encryption.html[Get an IP address of an external key management server for storage encryption]
// BURT-1476241 2022-August-12
. link:ensure_new_controllers_are_set_up_correctly.html[Confirm that the new controllers are set up correctly]
. link:set_up_storage_encryption_new_module.html[Set up Storage Encryption on the new controller module]
. link:set_up_netapp_volume_encryption_new_module.html[Set up NetApp Volume or Aggregate Encryption on the new controller module]
. link:decommission_old_system.html[Decommission the old system]
. link:resume_snapmirror_operations.html[Resume SnapMirror operations]
//BURT-1476241 13-Sep-2022
